### ISSUE TITLE
Demo APK

### ISSUE THREAD

**Issue by sl33pyC01E** [shubham0204/Segment-Anything-Android#1]
can you build a demo apk and post it in releases?

I'm not super proficient in android studio and if you already have it built

is it shareable 

and can you share it 

;-;

super neat project,
I think it would work well with the media pipe diffusion module

**Comment by shubham0204** [comment]
@sl33pyC01E I have built the APK and published it in a [release](https://github.com/shubham0204/Segment-Anything-Android/releases/tag/release_apk). Moreover, the app can now also read the models from the `assets` folder of the app.

**Comment by sl33pyC01E** [comment]
"ERROR: 
An error occurred: Error code - ORT_NO_SUCHFILE - message: Load model from /data/local/tmp/sam/ encoder_base_plus.onnx failed:Load model/data/local/tmp/sam/ encoder_base_plus.onnx failed. File doesn't exist"

is there anywhere I can find an onnx compiled SAM  model?
It seems like the app is looking in the wrong place or possibly with the wrong title

I appreciate your fast response and the work thus far though!!

**Comment by shubham0204** [comment]
There was a small glitch where the app was checking the presence of the model in the `assets` folder. I have fixed it, and uploaded the new version of the APK in the release. Please check and let me know if it works correctly.

**Comment by sl33pyC01E** [comment]
it works as intended now!
and i found the linked repo of .org files,

I really appreciate it!
