### ISSUE TITLE
Is there any flutter version?

### ISSUE THREAD

**Issue by yiptsangkin** [shubham0204/Segment-Anything-Android#2]

**Comment by shubham0204** [comment]
This repository will only maintain the Android app inference the Segment-Anything model. Did a quick Google search and found this Flutter package: https://pub.dev/packages/segment_anything

**Comment by yiptsangkin** [comment]
> This repository will only maintain the Android app inference the Segment-Anything model. Did a quick Google search and found this Flutter package: https://pub.dev/packages/segment_anything

i had seen its code, it only draw the mask on the image.

**Comment by yiptsangkin** [comment]
> This repository will only maintain the Android app inference the Segment-Anything model. Did a quick Google search and found this Flutter package: https://pub.dev/packages/segment_anything

ok, tks
